package:
  name: ska3-flight-latest
  version: 2025.0

build:
  noarch: generic

requirements:
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - aca_view
    - acis_taco
    - acis_thermal_check
    - acispy
    - agasc
    - backstop_history
    - chandra_aca
    - chandra_limits
    - chandra_maneuver
    - chandra_time
    - cheta
    - cxotime
    - fot-matlab
    - hopper
    - kadi
    - maude
    - mica
    - parse_cm
    - proseco
    - pyyaks
    - quaternion
    - ska-sphinx-theme
    - ska_arc5gl
    - ska_astro
    - ska_dbi
    - ska_file
    - ska_ftp
    - ska_numpy
    - ska_matplotlib
    - ska_parsecm
    - ska_quatutil
    - ska_shell
    - ska_sun
    - ska_tdb
    - ska3-template
    - ska_helpers
    - ska_path
    - ska_sync
    - sparkles
    - starcheck
    - testr
    - xija
