package:
  name: ska_ftp
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/ska_ftp


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - ska_helpers
    - testr
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - paramiko
    - testr
    - ska_helpers

test:
  imports:
    - Ska.ftp
    - ska_ftp

  requires:
    - pyyaks


about:
  home: https://github.com/sot/ska_ftp
