package:
  name: maude
  version:  {{ SKA_PKG_VERSION }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python


source:
  path: {{ SKA_TOP_SRC_DIR }}/maude


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - requests
    - six
    - scipy
    - numpy
    - pyyaks
    - ska.ftp
    - ska.tdb
    - chandra.time
    - testr

test:
  imports:
    - maude


about:
  home: https://github.com/sot/maude
