package:
  name: maude
  version:  {{ SKA_PKG_VERSION }}

build:
  noarch: python
  script_env:
    - SKA_TOP_SRC_DIR


source:
  path: {{ SKA_TOP_SRC_DIR }}/maude


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - requests
    - six
    - numpy
    - pyyaks
    - chandra.time
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - requests
    - six
    - scipy
    - numpy
    - pyyaks
    - ska.ftp
    - ska.tdb
    - chandra.time
    - testr

test:
  imports:
    - maude


about:
  home: git@github.com:sot/maude
