package:
  name: aimpoint_mon
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/aimpoint_mon


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - pytables
    - jinja2
    - numpy
    - matplotlib-base
    - astropy
    - chandra_time
    - kadi
    - pyyaks
    - mica
    - ska_dbi
    - ska_arc5gl
    - ska_shell
    - cheta
    - ska_helpers

about:
  home: https://github.com/sot/aimpoint_mon

