package:
  name: chandra_time
  version:  {{ SKA_PKG_VERSION }}

build:
  number: 1
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/chandra_time

# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - {{ compiler('cxx') }}
    - libcxx ==19.1.6
  host:
    - python
    - cython
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - ska_helpers # needed for duplicate_package_info
    - testr # needed for ska_helpers
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - cxotime
    - python
    - six
    - numpy
    - testr
    - ska_helpers

test:
  imports:
    - Chandra.Time
    - chandra_time


about:
  home: https://github.com/sot/chandra_time
  license: BSD
  summary: Chandra Time package
