package:
  name: chandra_time
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/chandra_time

# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - gxx_linux-64 # [linux]
    - libgcc-ng  # [linux]
    - clangxx_osx-64 # [osx]
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - cython
    - ska_helpers
    - testr
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - cxotime
    - python
    - six
    - numpy
    - testr
    - ska_helpers

test:
  imports:
    - Chandra.Time
    - chandra_time


about:
  home: https://github.com/sot/chandra_time
  license: BSD
  summary: Chandra Time package
