package:
  name: prompt-toolkit
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .
  skip: True  # [not win]

source:
  path: {{ SKA_TOP_SRC_DIR }}/prompt-toolkit


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm

  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - pygments
    - python >=3.6
    - six >=1.9.0
    - wcwidth

about:
  home: https://github.com/prompt-toolkit/python-prompt-toolkit.git
