package:
  name: ska_file  # lower case name of package, may contain '-' but no spaces
  version: {{ SKA_PKG_VERSION }}


build:
  script: pip install .
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/ska_file



requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - ska_helpers

  run:
    - python


test:
  imports:
    - Ska.File
    - ska_file

about:
  home: https://github.com/sot/ska_file
