channels:
  - conda-forge
dependencies:
  # note that ska3 packages should not be here, because this is used to build all ska3 packages
  - python                   # python version specified in the workflow
  - libarchive               # libarchive from defaults might not be good for mamba
  - mamba
  - setuptools_scm
  - gitpython
  - conda-build
  - jinja2
  - pyyaml
  - numpy
  - packaging
