package:
  name: hopper
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/hopper


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive

  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - quaternion
    - chandra_aca
    - pyyaks
    - chandra_maneuver
    - chandra_time
    - cxotime
    - parse_cm
    - astropy
    - testr

test:
  imports:
    - hopper

about:
  home: https://github.com/sot/hopper

