package:
  name: perigee_health_plots
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/perigee_health_plots

# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive

  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - numpy
    - astropy
    - jinja2
    - chandra_time
    - kadi
    - pyyaks
    - cheta
    - ska_shell
    - ska_report_ranges
    - ska_matplotlib
    - xija
    - testr

test:
  imports:
    - perigee_health_plots


about:
  home: https://github.com/sot/perigee_health_plots

