package:
  name: ska3-perl-latest
  version: 2025.0

build:
  skip: True  # [win]

requirements:
  run:
    - perl
    - perl-app-cpanminus
    - perl-core-deps
    - perl-ska-classic
    - xtime # [linux]
    - perl-extended-deps # [linux]
    - perl-pdl # [linux]
    - perl-io-tty # [linux]
    - perl-astro-fits-cfitsio-simple # [linux]
    - perl-astro-fits-cfitsio # [linux]
    - perl-chandra-time # [linux]
    - perl-cxc-sysarch # [linux]
    - perl-ska-convert # [linux]
    - perl-ska-web # [linux]
    - perl-ska-agasc # [linux]
    - perl-app-env-ascds # [linux]
    - perl-dbd-sybase # [linux]
    - perl-tk # [linux]
    - watch_cron_logs
    - task_schedule
