package:
  name: kadi
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/kadi


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - pytables
    - configobj
    - requests
    - django >=3.0
    - pyyaks
    - ska_dbi
    - ska_file
    - ska_ftp
    - ska_numpy
    - astropy
    - quaternion
    - chandra_time
    - cheta
    - numpy
    - mica
    - find_attitude
    - testr
    - ska_helpers

test:
  imports:
    - kadi


about:
  home: https://github.com/sot/kadi
  license: BSD
  summary: kadi
