package:
  name: ska-sphinx-theme
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/ska-sphinx-theme

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - sphinx

about:
  home: https://github.com/sot/ska-sphinx-theme
