
package:
  name: ska_sun  # lower case name of package, may contain '-' but no spaces
  version: {{ SKA_PKG_VERSION }}


build:
  script: pip install .
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/ska_sun



requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - ska_helpers
    - testr
  run:
    - python
    - ska_quatutil
    - chandra_time
    - quaternion
    - numpy
    - ska_helpers
    - testr

test:
  imports:
    - Ska.Sun
    - ska_sun

about:
  home: https://github.com/sot/ska_sun
