package:
  name: find_attitude
  version:  {{ SKA_PKG_VERSION }}

build:
  number: 1
  script: pip install .
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/find_attitude


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - testr
    - astropy
    - numpy
    - networkx
    - pytables
    - pyyaks
    - quaternion
    - ska_quatutil
#   - sherpa
    - ska_helpers

test:
  imports:
    - find_attitude


about:
  home: https://github.com/sot/find_attitude

