package:
  name: find_attitude
  version:  {{ SKA_PKG_VERSION }}

build:
  noarch: python
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/find_attitude


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - pip
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - testr
    - astropy
    - numpy
    - networkx
    - pytables
    - pyyaks
    - quaternion
    - ska.quatutil
    - sherpa
    - ska_helpers

test:
  imports:
    - find_attitude


about:
  home: git@github.com:sot/find_attitude

