package:
  name: testr
  version:  {{ SKA_PKG_VERSION }}

build:
  script: python setup.py install
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/testr


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - pytest
    # These are dependencies in the run_testr script but do not make these
    # dependencies for every single package that imports testr in setup.py.
    # - ska.file
    # - ska.shell
    # - pyyaks
    # - astropy

test:
  imports:
    - testr


about:
  home: https://github.com/sot/testr

