package:
  name: astromon
  version:  {{ SKA_PKG_VERSION }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  path: {{ SKA_TOP_SRC_DIR }}/astromon


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - pip
    - python
    - setuptools
    - setuptools_scm
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - setuptools_scm
    - numpy
    - scipy
    - matplotlib
    - sqlite
    - jinja2
    - astropy
    - filelock
    - pytables
    - beautifulsoup4
    - json5
    - regions
    - astroquery
    - kadi
    - cxotime
    - ska_helpers
    - quaternion
    - chandra_aca
    - pyyaks
    - ska_arc5gl
    - ska_dbi
    - cheta
    - ska.matplotlib
    - ska.tdb
    - ska.shell
    - ska.file
    - sphinx-argparse

about:
  home: https://github.com/sot/astromon
  summary: Tools for absolute astrometry monitoring
  dev_url: https://github.com/sot/astromon
  doc_url: https://sot.github.io/astromon
