package:
  name: sherpa
  version: {{ environ.get('SKA_PKG_VERSION') }}

source:
  git_url: https://github.com/sherpa/sherpa.git
  git_rev: {{ environ.get('SKA_PKG_VERSION') }}

build:
  number: {{ environ.get('SKA_BUILD_NUMBER', 0) }}

build:
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make
    - bison
    - flex

  host:
    - python
    - numpy
    - setuptools
    - six

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - setuptools
    - pytest
    - six

about:
  home: https://cxc.cfa.harvard.edu/sherpa/
  dev_url: https://github.com/sherpa/sherpa
  summary: Sherpa is the CIAO modeling and fitting application. It enables the user to construct complex models from simple definitions and fit those models to data, using a variety of statistics and optimization methods
  license: GPLv3
