---
package:
  name: ska3-aca
  version: 2025.8

build:
  noarch: generic

requirements:
  run:
    # The following packages are common to ska3-<flight|matlab|aca>
    - aca_view ==0.16.0
    - acis_taco ==4.2.3
    - acis_thermal_check ==5.3.1
    - acispy ==2.8.0
    - agasc ==4.23.0
    - backstop_history ==3.2.1
    - chandra_aca ==4.51.1
    - chandra_limits ==0.10.1
    - chandra_maneuver ==4.3.1
    - chandra_time ==4.2.0
    - cheta ==4.63.2
    - cxotime ==3.10.1
    - fot-matlab ==2.4.1
    - hopper ==4.6.0
    - kadi ==7.17.1
    - maude ==3.14.0
    - mica ==4.39.0
    - parse_cm ==3.17.0
    - proseco ==5.16.1
    - pyyaks ==4.5.0
    - quaternion ==4.3.1
    - ska-sphinx-theme ==1.3.0
    - ska3-core ==2025.5
    - ska3-template ==2022.06.02
    - ska_arc5gl ==4.0.1
    - ska_astro ==4.0.0
    - ska_dbi ==5.2.0
    - ska_file ==4.0.0
    - ska_ftp ==4.0.1
    - ska_helpers ==0.19.0
    - ska_matplotlib ==4.0.1
    - ska_numpy ==4.0.1
    - ska_parsecm ==4.0.1
    - ska_path ==3.1.2
    - ska_quatutil ==4.0.0
    - ska_shell ==4.1.1
    - ska_sun ==3.15.0
    - ska_sync ==4.13.0
    - ska_tdb ==4.1.0
    - sparkles ==4.29.0
    - starcheck ==14.14.0
    - testr ==4.13.0
    - xija ==4.33.2
    # The following packages are specific to ACA
    - attitude_error_mon
    - aca_hi_bgd
    - aca_weekly_report
    - acq_stat_reports
    - acdc
    - aimpoint_mon
    - aperoll
    - astromon
    - annie
    - fid_drift_mon
    - find_attitude
    - fss_check
    - jobwatch
    - kalman_watch
    - perigee_health_plots
    - schedule_view3
    - ska_report_ranges
    - ska_trend
    - skare3_tools
    - vv_trending
    - twiki-wg
    - obc_rate_noise_plots
