package:
  name: twiki-wg
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/twiki-wg


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - requests
    - ska_ftp
    - cxotime
    - testr
    - ska_helpers

test:
  imports:
    - twiki_wg


about:
  home: https://github.com/sot/twiki-wg

