package:
  name: chandra.time
  version:  {{ GIT_DESCRIBE_TAG }}

build:
  script_env:
    - SKA_TOP_SRC_DIR
  preserve_egg_dir: yes # (default no)
  entry_points:
    - entry = conda_version_test.manual_entry:main

source:
  path: {{ SKA_TOP_SRC_DIR }}/Chandra.Time


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - cython >=0.20.1
    - six
    - numpy
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - setuptools
    - six
    - numpy
    - astropy
    - testr

test:
  imports:
    - Chandra.Time


about:
  home: https://github.com/sot/Chandra.Time
  license: BSD
  summary: Chandra Time package
