package:
  name: ska_sync
  version: {{ SKA_PKG_VERSION }}


build:
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/ska_sync



requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python
    - yaml
    - ska_path
    - ska_helpers

test:
  imports:
    - ska_sync

about:
  home: https://github.com/sot/ska_sync
