---
package:
  name: ska3-matlab
  version: 2025.2

build:
  noarch: generic

requirements:
  run:
    - aca_view ==0.16.0
    - acis_taco ==4.2.3
    - acis_thermal_check ==5.2.0
    - acispy ==2.7.0
    - agasc ==4.22.0
    - backstop_history ==3.2.1
    - chandra_aca ==4.48.1
    - chandra_limits ==0.10.0
    - chandra_maneuver ==4.3.0
    - chandra_time ==4.1.2
    - cheta ==4.62.3
    - cxotime ==3.9.2
    - fot-matlab ==2.4.1
    - hopper ==4.6.0
    - kadi ==7.14.1
    - maude ==3.12.1
    - mica ==4.38.1
    - parse_cm ==3.16.2
    - proseco ==5.16.1
    - pyyaks ==4.5.0
    - quaternion ==4.3.1
    - ska-sphinx-theme ==1.3.0
    - ska3-core ==2025.2
    - ska3-template ==2022.06.02
    - ska_arc5gl ==4.0.1
    - ska_astro ==4.0.0
    - ska_dbi ==5.1.1
    - ska_file ==4.0.0
    - ska_ftp ==4.0.1
    - ska_helpers ==0.17.0
    - ska_matplotlib ==4.0.1
    - ska_numpy ==4.0.1
    - ska_parsecm ==4.0.1
    - ska_path ==3.1.2
    - ska_quatutil ==4.0.0
    - ska_shell ==4.0.1
    - ska_sun ==3.15.0
    - ska_sync ==4.13.0
    - ska_tdb ==4.1.0
    - sparkles ==4.28.1
    - starcheck ==14.12.0
    - testr ==4.13.0
    - xija ==4.32.0
