---
package:
  name: ska3-matlab
  version: "2022.10.1"

build:
  noarch: generic

requirements:
  run:
    - aca_hi_bgd ==0.1.6
    - aca_view ==0.10.0
    - aca_weekly_report ==0.1.6
    - acdc ==4.8.1
    - acis_taco ==4.2.2
    - acis_thermal_check ==4.3.1
    - acispy ==2.5.0
    - agasc ==4.12.1
    - aimpoint_mon ==1.0.1
    - astromon ==1.0.1
    - annie ==0.11.1
    - backstop_history ==3.1.0
    - chandra.cmd_states ==3.17.0
    - chandra.maneuver ==3.8.0
    - chandra.time ==4.0.1
    - chandra_aca ==4.37.1
    - cxotime ==3.3.0
    - find_attitude ==3.4.2
    - fot-matlab ==2.1.1
    - hopper ==4.5.2
    - jobwatch ==0.10.0
    - kadi ==7.0.1
    - kalman_watch ==0.1.0
    - maude ==3.10.3
    - mica ==4.31.0
    - parse_cm ==3.9.1
    - perigee_health_plots ==0.3.1
    - proseco ==5.8.0
    - pyyaks ==4.5.0
    - quaternion ==4.1.1
    - ska-sphinx-theme ==1.3.0
    - ska.arc5gl ==3.3.0
    - ska.astro ==3.3.0
    - ska.dbi ==4.1.0
    - ska.engarchive ==4.57.0
    - ska.file ==3.4.5
    - ska.ftp ==3.6.0
    - ska.matplotlib ==3.15.0
    - ska.numpy ==3.9.1
    - ska.parsecm ==3.4.0
    - ska.quatutil ==3.4.0
    - ska.report_ranges ==0.4.0
    - ska.shell ==3.5.1
    - ska.sun ==3.8.1
    - ska.tdb ==3.6.1
    - ska3-core ==2022.6
    - ska3-template ==2022.06.02
    - ska_helpers ==0.6.1
    - ska_path ==3.1.2
    - ska_sync ==4.10.0
    - skare3_tools ==1.0.7
    - sparkles ==4.20.0
    - starcheck ==13.16.0
    - testr ==4.11.1
    - xija ==4.27.0
