package:
  name: chandra_cmd_states
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/chandra_cmd_states


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - ska_helpers
    - testr
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - chandra_time
    - ska_dbi
    - ska_file
    - chandra_maneuver
    - quaternion
    - ska_sun
    - ska_parsecm
    - ska_numpy
    - ska_ftp
#    - kadi
    - testr

test:
  imports:
    - Chandra.cmd_states
    - chandra_cmd_states


about:
  home: https://github.com/sot/cmd_states
