package:
  name: ska_helpers
  version: {{ SKA_PKG_VERSION }}


build:
  script: pip install . --single-version-externally-managed --record=record.txt
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/ska_helpers



requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python


about:
  home: https://github.com/sot/ska_helpers
