
package:
  name: ska_shell  # lower case name of package, may contain '-' but no spaces
  version: {{ SKA_PKG_VERSION }}

build:
  noarch: python
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/ska_shell
  
requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - ska_helpers
    - testr

  run:
    - python
    - six
    - pexpect
    - testr
    - ska_helpers

test:
  imports:
    - Ska.Shell
    - ska_shell

about:
  home: https://github.com/sot/ska_shell

