package:
  name: ska.parsecm
  version:  {{ SKA_PKG_VERSION }}

build:
  noarch: python
  script_env:
    - SKA_TOP_SRC_DIR
  preserve_egg_dir: yes # (default no)

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.ParseCM


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - pip <10.0
    - python
    - six
    - chandra.time
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - chandra.time

test:
  imports:
    - Ska.ParseCM


about:
  home: https://github.com/sot/Ska.ParseCM

