package:
  name: ska.engarchive
  version:  {{ GIT_DESCRIBE_TAG }}{% if GIT_DESCRIBE_NUMBER != '0'%}_dev{{GIT_DESCRIBE_NUMBER}}{% endif %}

build:
  noarch: python
  script_env:
    - SKA_TOP_SRC_DIR
  preserve_egg_dir: yes # (default no)

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.engarchive


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - pip <10.0
    - python
    - setuptools
    - six
    - numpy
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - numpy
    - ipython
    - ipyparallel
    - pytables
    - tables3_api
    - chandra.time
    - ska.numpy
    - ska.dbi
    - astropy
    - testr

test:
  imports:
    - Ska.engarchive


about:
  home: https://github.com/sot/eng_archive


