package:
  name: aca_weekly_report
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/aca_weekly_report

# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive

  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - numpy
    - astropy
    - jinja2
    - chandra_time
    - kadi
    - mica
    - ska_dbi
    - cheta
    - ska_matplotlib
    - ska_numpy
    - proseco
    - pyyaks
    - testr

test:
  imports:
    - aca_weekly_report


about:
  home: https://github.com/sot/aca_weekly_report

