package:
  name: ska3-dev
  version: 0.1.5

build:
  noarch: generic

requirements:
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
  # Ska packages
   - agasc
   - annie
   - acisfp_check
   - acis_taco
   - acis_thermal_check
   - backstop_history
   - chandra.cmd_states
   - chandra.maneuver
   - chandra.time
   - chandra_aca
   - cxotime
   - dea_check
   - dpa_check
   - hopper
   - kadi
   - maude
   - mica
   - parse_cm
   - psmc_check
   - quaternion
   - ska.arc5gl
   - ska.astro
   - ska.dbi
   - ska.engarchive
   - ska.file
   - ska.ftp
   - ska.matplotlib
   - ska.numpy
   - ska.parsecm
   - ska.quatutil
   - ska.shell
   - ska.sun
   - ska.tdb
   - ska3-template
   - ska_path
   - ska_sync
   - pyyaks
   - tables3_api
   - testr
   - xija
  # Installed from Ska
   - sherpa
  # Core packages that we want whether or not they are dependencies of Ska packages
   - astropy
   - beautifulsoup4
   - bokeh
   - cython
   - django
   - git
   - gitpython
   - h5py
   - hdf5
   - ipython
   - jinja2
   - jupyter
   - jupyter_client
   - jupyter_console
   - line_profiler
   - llvmlite
   - lxml
   - matplotlib
   - nb_conda
   - nbconvert
   - networkx
   - notebook
   - numba
   - numexpr
   - numpy
   - numpydoc
   - openssl
   - pandas
   - pep8
   - pillow
   - pip
   - pyflakes
   - pylint
   - pyyaml
   - qt
   - qtconsole
   - readline
   - requests
   - runipy
   - scikit-learn
   - scipy
   - setuptools
   - six
   - sphinx
   - spyder
   - sqlite
   - tk
   - yaml
   - zeromq
