package:
  name: ska_path  # lower case name of package, may contain '-' but no spaces
  version: {{ SKA_PKG_VERSION }}


build:
  script: python setup.py install
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/ska_path



requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python


test:
  imports:
    - ska_path

about:
  home: https://github.com/sot/ska_path
