{% set name = "jplephem" %}
{% set version = "2.8" %}
{% set sha256 = "ccb21595d59867dff5aaddd9fb812ce2e870c26a65e161e310bb85e819e4a1d6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001_use-setuptools.patch

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy ==1.12
  run:
    - python
    - numpy ==1.12

test:
  requires:
    - curl
  imports:
    - jplephem
  commands:
    - curl -sS -O https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/a_old_versions/de421.bsp
    - curl -sS -O https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430.bsp
    - curl -sS -O https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/a_old_versions/de405.bsp
    - curl -sS -O ftp://ssd.jpl.nasa.gov/pub/eph/planets/test-data/430/testpo.430
    - python -m unittest discover jplephem.test
    - python -m jplephem.jpltest

about:
  home: https://pypi.python.org/pypi/jplephem
  license: MIT
  summary: "Python version of NASA DE4xx ephemerides, the basis for the Astronomical Alamanac"

extra:
  recipe-maintainers:
    - juanlu001
    - brandon-rhodes
    - jochym
