package:
  name: chandra_maneuver
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/chandra_maneuver


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - ska_helpers
    - testr
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - quaternion
    - chandra_time
    - ska_sun
    - ska_helpers
test:
  requires:
    - agasc
    - cheta
    - testr
  imports:
    - Chandra.Maneuver
    - chandra_maneuver


about:
  home: https://github.com/sot/chandra_maneuver
