package:
  name: cheta
  version:  {{ SKA_PKG_VERSION }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  path: {{ SKA_TOP_SRC_DIR }}/cheta

# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - ska_helpers

  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - numpy
    - ipython
    - ipyparallel
    - pytables
    - chandra_time
    - ska_numpy
    - ska_dbi
    - astropy
    - testr
    - jinja2
    - pyyaks
    - pyyaml

test:
  imports:
    - Ska.engarchive
    - cheta

about:
  home: https://github.com/sot/cheta


