---
package:
  name: ska3-flight
  version: 2024.7

build:
  noarch: generic

requirements:
  run:
    - aca_view ==0.14.1
    - acis_taco ==4.2.3
    - acis_thermal_check ==5.1.1
    - acispy ==2.6.0
    - agasc ==4.20.0
    - backstop_history ==3.2.1
    - chandra_aca ==4.45.1
    - chandra_cmd_states ==4.1.0
    - chandra_limits ==0.9.1
    - chandra_maneuver ==4.2.0
    - chandra_time ==4.1.2
    - cheta ==4.62.0
    - cxotime ==3.8.0
    - find_attitude ==3.4.4
    - fot-matlab ==2.4.0
    - hopper ==4.6.0
    - kadi ==7.10.1
    - maude ==3.11.1
    - mica ==4.35.2
    - parse_cm ==3.15.0
    - proseco ==5.13.2
    - pyyaks ==4.5.0
    - quaternion ==4.3.1
    - ska-sphinx-theme ==1.3.0
    - ska_arc5gl ==4.0.1
    - ska_astro ==4.0.0
    - ska_dbi ==5.1.0
    - ska_file ==4.0.0
    - ska_ftp ==4.0.1
    - ska_helpers ==0.16.0
    - ska_matplotlib ==4.0.1
    - ska_numpy ==4.0.1
    - ska_parsecm ==4.0.1
    - ska_path ==3.1.2
    - ska_quatutil ==4.0.0
    - ska_shell ==4.0.1
    - ska_sun ==3.14.0
    - ska_sync ==4.12.0
    - ska_tdb ==4.0.0
    - ska3-core ==2024.7
    - ska3-template ==2022.06.02
    - sparkles ==4.26.1
    - starcheck ==14.10.0
    - testr ==4.12.0
    - xija ==4.32.0
