---
package:
  name: ska3-flight
  version: 2022.1

build:
  noarch: generic

requirements:
  run:
    - aca_hi_bgd ==0.1.5
    - aca_view ==0.9.0
    - aca_weekly_report ==0.1.5
    - acdc ==4.8.0
    - acis_taco ==4.2.0
    - acis_thermal_check ==4.0.0
    - acispy ==2.3.0
    - agasc ==4.11.4
    - annie ==0.11.0
    - backstop_history ==1.5.1
    - chandra.cmd_states ==3.17.0
    - chandra.maneuver ==3.8.0
    - chandra.time ==4.0.0
    - chandra_aca ==4.34.0
    - cxotime ==3.2.5
    - find_attitude ==3.4.0
    - hopper ==4.5.2
    - jobwatch ==0.6.0
    - kadi ==5.8.0
    - maude ==3.7.0
    - mica ==4.28.0
    - parse_cm ==3.7.1
    - perigee_health_plots ==0.2.1
    - proseco ==5.4.0
    - pyyaks ==4.5.0
    - quaternion ==4.1.0
    - ska-sphinx-theme ==1.3.0
    - ska.arc5gl ==3.2.0
    - ska.astro ==3.3.0
    - ska.dbi ==4.1.0
    - ska.engarchive ==4.54.0
    - ska.file ==3.4.5
    - ska.ftp ==3.6.0
    - ska.matplotlib ==3.13.0
    - ska.numpy ==3.9.0
    - ska.parsecm ==3.4.0
    - ska.quatutil ==3.4.0
    - ska.report_ranges ==0.4.0
    - ska.shell ==3.5.0
    - ska.sun ==3.7.0
    - ska.tdb ==3.6.0
    - ska3-core ==2022.1
    - ska3-template ==2019.09.03
    - ska_helpers ==0.5.0
    - ska_path ==3.1.2
    - ska_sync ==4.9.1
    - skare3_tools ==1.0.5
    - sparkles ==4.13.1
    - starcheck ==13.14.0
    - testr ==4.6.0
    - xija ==4.24.0
