---
package:
  name: ska3-flight
  version: "2026.0"

build:
  noarch: generic

requirements:
  run:
    - aca_view ==0.18.0
    - acis_taco ==4.2.3
    - acis_thermal_check ==5.3.2
    - acispy ==2.8.0
    - agasc ==4.23.3
    - backstop_history ==3.2.1
    - chandra_aca ==4.52.1
    - chandra_limits ==0.11.1
    - chandra_maneuver ==4.4.1
    - chandra_time ==4.3.1
    - cheta ==4.66.1
    - cxotime ==3.11.1
    - fot-matlab ==2.5.1
    - hopper ==4.6.0
    - kadi ==7.17.6
    - maude ==3.15.0
    - mica ==4.39.2
    - parse_cm ==3.18.1
    - proseco ==5.17.1
    - pyyaks ==4.5.1
    - quaternion ==4.3.1
    - razl ==0.1.0
    - ska-sphinx-theme ==1.3.0
    - ska3-core ==2026.0
    - ska3-template ==2022.06.02
    - ska_arc5gl ==4.0.1
    - ska_astro ==4.0.0
    - ska_dbi ==5.2.0
    - ska_file ==4.0.0
    - ska_ftp ==4.0.1
    - ska_helpers ==0.20.1
    - ska_matplotlib ==4.0.1
    - ska_numpy ==4.0.2
    - ska_parsecm ==4.0.1
    - ska_path ==3.1.2
    - ska_quatutil ==4.0.0
    - ska_shell ==4.1.1
    - ska_sun ==3.15.0
    - ska_sync ==4.13.0
    - ska_tdb ==4.1.0
    - sparkles ==4.31.1
    - starcheck ==14.15.0
    - testr ==4.13.0
    - xija ==4.35.0
