---
package:
  name: ska3-flight
  version: 2024.11

build:
  noarch: generic

requirements:
  run:
    - aca_view ==0.14.2
    - acis_taco ==4.2.3
    - acis_thermal_check ==5.1.1
    - acispy ==2.7.0
    - agasc ==4.21.2
    - backstop_history ==3.2.1
    - chandra_aca ==4.47.0
    - chandra_limits ==0.9.2
    - chandra_maneuver ==4.3.0
    - chandra_time ==4.1.2
    - cheta ==4.62.1
    - cxotime ==3.9.0
    - fot-matlab ==2.4.1
    - hopper ==4.6.0
    - kadi ==7.13.0
    - maude ==3.11.1
    - mica ==4.37.0
    - parse_cm ==3.16.0
    - proseco ==5.15.0
    - pyyaks ==4.5.0
    - quaternion ==4.3.1
    - ska-sphinx-theme ==1.3.0
    - ska_arc5gl ==4.0.1
    - ska_astro ==4.0.0
    - ska_dbi ==5.1.0
    - ska_file ==4.0.0
    - ska_ftp ==4.0.1
    - ska_helpers ==0.17.0
    - ska_matplotlib ==4.0.1
    - ska_numpy ==4.0.1
    - ska_parsecm ==4.0.1
    - ska_path ==3.1.2
    - ska_quatutil ==4.0.0
    - ska_shell ==4.0.1
    - ska_sun ==3.15.0
    - ska_sync ==4.13.0
    - ska_tdb ==4.1.0
    - ska3-core ==2024.11
    - ska3-template ==2022.06.02
    - sparkles ==4.27.1
    - starcheck ==14.12.0
    - testr ==4.12.0
    - xija ==4.32.0
