---
package:
  name: ska3-flight
  version: 2020.13+shiny

build:
  noarch: generic

requirements:
  run:
    - aca_view ==0.4.0
    - acdc ==4.6.0
    - acis_taco ==4.2.0
    - acis_thermal_check ==3.2.1
    - acisfp_check ==3.2.0
    - acispy ==2.0.1.dev12+gc5410da
    - agasc ==4.9.0
    - annie ==0.11.0
    - backstop_history ==1.2.0
    - bep_pcb_check ==3.0.0
    - chandra.cmd_states ==3.16.0
    - chandra.maneuver ==3.8.0
    - chandra.time ==4.0.0
    - chandra_aca ==4.30.0
    - cxotime ==3.2.2
    - dea_check ==3.1.0
    - dpa_check ==3.0.0
    - fep1_actel_check ==3.0.0
    - fep1_mong_check ==3.0.0
    - find_attitude ==3.4.0
    - hopper ==4.5.0
    - kadi ==5.3.0
    - maude ==3.4.0
    - mica ==4.22.0
    - parse_cm ==3.5.2
    - proseco ==4.9.0
    - psmc_check ==3.0.0
    - pyyaks ==4.5.0
    - quaternion ==3.6.0
    - ska.arc5gl ==3.1.5
    - ska.astro ==3.3.0
    - ska.dbi ==4.1.0
    - ska.engarchive ==4.49.0
    - ska.file ==3.4.5
    - ska.ftp ==3.6.0
    - ska.matplotlib ==3.12.0
    - ska.numpy ==3.9.0
    - ska.parsecm ==3.4.0
    - ska.quatutil ==3.4.0
    - ska.shell ==3.5.0
    - ska.sun ==3.6.0
    - ska.tdb ==3.6.0
    - ska3-core ==2020.13+shiny
    - ska3-template ==2019.09.03
    - ska_helpers ==0.2.0
    - ska_path ==3.1.2
    - ska_sync ==4.7.0
    - sparkles ==4.7.0
    - starcheck ==13.7.1
    - testr ==4.4.0
    - xija ==4.20.1
