---
package:
  name: ska3-core
  version: 2023.0

requirements:
  run:
    - _libgcc_mutex ==0.1  # [linux]
    - _openmp_mutex ==4.5  # [linux]
    - alabaster ==0.7.12
    - alsa-lib ==1.2.6.1  # [linux]
    - anyio ==3.6.2
    - appnope ==0.1.3  # [osx]
    - argon2-cffi ==21.3.0
    - argon2-cffi-bindings ==21.2.0
    - asgiref ==3.3.4
    - astroid ==2.12.13
    - astropy ==5.1.1
    - astropy-healpix ==0.7
    - astropy-sphinx-theme ==1.1
    - astroquery ==0.4.6
    - asttokens ==2.1.0
    - attr ==2.5.1  # [linux]
    - attrs ==22.1.0
    - autopep8 ==2.0.0
    - babel ==2.11.0
    - backcall ==0.2.0
    - backports ==1.0
    - backports.functools_lru_cache ==1.6.4
    - backports.zoneinfo ==0.2.1
    - bcrypt ==3.2.0
    - beautifulsoup4 ==4.11.1
    - black ==22.10.0
    - bleach ==5.0.1
    - blinker ==1.5
    - blosc ==1.21.1
    - bokeh ==3.0.2
    - brotli ==1.0.9
    - brotli-bin ==1.0.9
    - brotlipy ==0.7.0
    - bzip2 ==1.0.8
    - c-ares ==1.18.1
    - ca-certificates ==2022.10.11
    - cached-property ==1.5.2
    - cached_property ==1.5.2
    - cctools ==973.0.1  # [osx]
    - cctools_osx-64 ==973.0.1  # [osx]
    - certifi ==2022.9.24
    - cffi ==1.15.1
    - chardet ==5.0.0
    - charset-normalizer ==2.1.1
    - click ==8.1.3
    - colorama ==0.4.6
    - comm ==0.1.0
    - commonmark ==0.9.1
    - conda ==22.9.0
    - conda-build ==3.23.1
    - conda-package-handling ==1.9.0
    - configobj ==5.0.6
    - contourpy ==1.0.6
    - cryptography ==38.0.3
    - cycler ==0.11.0
    - cython ==0.29.32
    - dbus ==1.13.6  # [linux]
    - debugpy ==1.6.3
    - decorator ==5.1.1
    - defusedxml ==0.7.1
    - dill ==0.3.6
    - django ==3.1.7
    - docutils ==0.19
    - docxtpl ==0.11.5
    - entrypoints ==0.4
    - et_xmlfile ==1.0.1
    - exceptiongroup ==1.0.4
    - executing ==1.2.0
    - expat ==2.5.0  # [linux]
    - fftw ==3.3.10  # [linux]
    - filelock ==3.8.0
    - flake8 ==5.0.4
    - flit-core ==3.8.0
    - fmt ==9.1.0
    - font-ttf-dejavu-sans-mono ==2.37  # [linux]
    - font-ttf-inconsolata ==3.000  # [linux]
    - font-ttf-source-code-pro ==2.038  # [linux]
    - font-ttf-ubuntu ==0.83  # [linux]
    - fontconfig ==2.14.1  # [linux]
    - fonts-conda-ecosystem ==1  # [linux]
    - fonts-conda-forge ==1  # [linux]
    - fonttools ==4.38.0
    - freetype ==2.12.1
    - future ==0.18.2
    - gettext ==0.21.1
    - giflib ==5.2.1
    - gitdb ==4.0.9
    - gitpython ==3.1.29
    - glib ==2.74.1
    - glib-tools ==2.74.1
    - glob2 ==0.7
    - gst-plugins-base ==1.20.3
    - gstreamer ==1.20.3
    - h5py ==3.7.0
    - hdf5 ==1.12.2
    - html5lib ==1.1
    - icu ==70.1
    - idna ==3.4
    - imagesize ==1.4.1
    - importlib-metadata ==5.0.0
    - importlib_metadata ==5.0.0
    - importlib_resources ==5.10.0
    - iniconfig ==1.1.1
    - ipykernel ==6.18.0
    - ipympl ==0.9.2
    - ipyparallel ==6.3.0
    - ipython ==8.6.0
    - ipython_genutils ==0.2.0
    - ipywidgets ==8.0.2
    - isort ==5.10.1
    - jack ==1.9.18  # [linux]
    - jaraco.classes ==3.2.3
    - jedi ==0.18.1
    - jeepney ==0.8.0  # [linux]
    - jinja2 ==3.1.2
    - jira ==3.4.1
    - joblib ==1.2.0
    - jpeg ==9e
    - jplephem ==2.18
    - json5 ==0.9.5
    - jsonschema ==4.17.0
    - jupyter ==1.0.0
    - jupyter_client ==7.4.7
    - jupyter_console ==6.4.4
    - jupyter_core ==5.0.0
    - jupyter_server ==1.23.3
    - jupyterlab ==3.5.0
    - jupyterlab_pygments ==0.2.2
    - jupyterlab_server ==2.16.3
    - jupyterlab_widgets ==3.0.3
    - kaleido-core ==0.2.1
    - keyring ==23.11.0
    - keyutils ==1.6.1  # [linux]
    - kiwisolver ==1.4.4
    - krb5 ==1.19.3
    - lazy-object-proxy ==1.8.0
    - lcms2 ==2.14
    - ld64 ==609  # [osx]
    - ld64_osx-64 ==609  # [osx]
    - ld_impl_linux-64 ==2.39  # [linux]
    - lerc ==4.0.0
    - libarchive ==3.5.2
    - libblas ==3.9.0
    - libbrotlicommon ==1.0.9
    - libbrotlidec ==1.0.9
    - libbrotlienc ==1.0.9
    - libcap ==2.64  # [linux]
    - libcblas ==3.9.0
    - libclang ==14.0.6
    - libclang13 ==14.0.6
    - libcups ==2.3.3  # [linux]
    - libcurl ==7.86.0
    - libcxx ==14.0.6  # [osx]
    - libdb ==6.2.32  # [linux]
    - libdeflate ==1.14
    - libedit ==3.1.20191231
    - libev ==4.33
    - libevent ==2.1.10  # [linux]
    - libffi ==3.4.2
    - libflac ==1.3.4  # [linux]
    - libgcc-ng ==12.2.0  # [linux]
    - libgfortran ==5.0.0  # [osx]
    - libgfortran-ng ==12.2.0  # [linux]
    - libgfortran5 ==11.3.0  # [osx]
    - libgfortran5 ==12.2.0  # [linux]
    - libglib ==2.74.1
    - libgomp ==12.2.0  # [linux]
    - libiconv ==1.17
    - liblapack ==3.9.0
    - liblief ==0.12.3
    - libllvm11 ==11.1.0
    - libllvm14 ==14.0.6
    - libmamba ==1.0.0
    - libmambapy ==1.0.0
    - libnghttp2 ==1.47.0
    - libnsl ==2.0.0  # [linux]
    - libogg ==1.3.4
    - libopenblas ==0.3.21
    - libopus ==1.3.1
    - libpng ==1.6.39
    - libpq ==14.5
    - libsndfile ==1.0.31  # [linux]
    - libsodium ==1.0.18
    - libsolv ==0.7.22
    - libsqlite ==3.40.0
    - libssh2 ==1.10.0
    - libstdcxx-ng ==12.2.0  # [linux]
    - libtiff ==4.4.0
    - libtool ==2.4.6  # [linux]
    - libudev1 ==252  # [linux]
    - libuuid ==2.32.1  # [linux]
    - libuv ==1.44.2
    - libvorbis ==1.3.7
    - libwebp ==1.2.4
    - libwebp-base ==1.2.4
    - libxcb ==1.13
    - libxkbcommon ==1.0.3  # [linux]
    - libxml2 ==2.10.3
    - libxslt ==1.1.37
    - libzlib ==1.2.13
    - line_profiler ==4.0.1
    - llvm-openmp ==15.0.5  # [osx]
    - llvmlite ==0.39.1
    - lxml ==4.9.1
    - lz4-c ==1.9.3
    - lzo ==2.10
    - mamba ==1.0.0
    - markupsafe ==2.1.1
    - mathjax ==2.7.7
    - matplotlib ==3.6.2
    - matplotlib-base ==3.6.2
    - matplotlib-inline ==0.1.6
    - mccabe ==0.7.0
    - mistune ==2.0.4
    - more-itertools ==9.0.0
    - mpld3 ==0.5.8
    - munkres ==1.1.4
    - mypy_extensions ==0.4.3
    - mysql-common ==8.0.31
    - mysql-libs ==8.0.31
    - nb_conda ==2.2.1
    - nb_conda_kernels ==2.3.1
    - nbclassic ==0.4.8
    - nbclient ==0.7.0
    - nbconvert ==7.2.5
    - nbconvert-core ==7.2.5
    - nbconvert-pandoc ==7.2.5
    - nbformat ==5.7.0
    - ncurses ==6.3
    - nest-asyncio ==1.5.6
    - networkx ==2.8.8
    - nodejs ==18.12.1
    - nomkl ==1.0  # [linux]
    - nose ==1.3.7
    - notebook ==6.5.2
    - notebook-shim ==0.2.2
    - nspr ==4.32
    - nss ==3.78
    - numba ==0.56.4
    - numexpr ==2.8.3
    - numpy ==1.23.5
    - numpydoc ==1.5.0
    - oauthlib ==3.2.2
    - openjpeg ==2.5.0
    - openpyxl ==3.0.10
    - openssl ==1.1.1s
    - packaging ==21.3
    - pandas ==1.5.1
    - pandoc ==2.19.2
    - pandocfilters ==1.5.0
    - paramiko ==2.8.1
    - parso ==0.8.3
    - patch ==2.7.6
    - patchelf ==0.17.0  # [linux]
    - pathspec ==0.10.2
    - pcre2 ==10.40
    - pexpect ==4.8.0
    - pickleshare ==0.7.5
    - pillow ==9.2.0
    - pip ==22.3.1
    - pkginfo ==1.8.3
    - pkgutil-resolve-name ==1.3.10
    - platformdirs ==2.5.2
    - plotly ==5.11.0
    - pluggy ==1.0.0
    - ply ==3.11
    - portaudio ==19.6.0  # [linux]
    - prometheus_client ==0.15.0
    - prompt-toolkit ==3.0.33
    - prompt_toolkit ==3.0.33
    - psutil ==5.9.4
    - pthread-stubs ==0.4
    - ptyprocess ==0.7.0
    - pulseaudio ==14.0  # [linux]
    - pure_eval ==0.2.2
    - py-lief ==0.12.3
    - pybind11-abi ==4
    - pycodestyle ==2.9.1
    - pycosat ==0.6.4
    - pycparser ==2.21
    - pycrypto ==2.6.1
    - pyerfa ==2.0.0.1
    - pyflakes ==2.5.0
    - pygments ==2.13.0
    - pyjwt ==2.6.0
    - pylint ==2.15.6
    - pynacl ==1.5.0
    - pyopenssl ==22.1.0
    - pyparsing ==3.0.9
    - pyqt ==5.15.7
    - pyqt5-sip ==12.11.0
    - pyqtgraph ==0.13.1
    - pyrsistent ==0.19.2
    - pysocks ==1.7.1
    - pytables ==3.7.0
    - pytest ==7.2.0
    - python ==3.10.8
    - python-dateutil ==2.8.2
    - python-docx ==0.8.11
    - python-fastjsonschema ==2.16.2
    - python-kaleido ==0.2.1
    - python-libarchive-c ==4.0
    - python_abi ==3.10
    - pytoolconfig ==1.2.2
    - pytz ==2022.6
    - pyvo ==1.4
    - pyyaml ==6.0
    - pyzmq ==24.0.1
    - qt ==5.15.4
    - qt-main ==5.15.4
    - qt-webengine ==5.15.4
    - qtconsole ==5.4.0
    - qtconsole-base ==5.4.0
    - qtpy ==2.3.0
    - readline ==8.1.2
    - regions ==0.6
    - reproc ==14.2.3
    - reproc-cpp ==14.2.3
    - requests ==2.28.1
    - requests-oauthlib ==1.3.1
    - requests-toolbelt ==0.10.1
    - ripgrep ==13.0.0
    - rope ==1.4.0  # [linux]
    - rope ==1.5.0  # [osx]
    - ruamel_yaml ==0.15.80
    - scikit-learn ==1.1.3
    - scipy ==1.9.3
    - secretstorage ==3.3.3  # [linux]
    - send2trash ==1.8.0
    - setuptools ==65.5.1
    - setuptools-scm ==7.0.5
    - setuptools_scm ==7.0.5
    - sherpa ==4.15.0
    - sigtool ==0.1.3  # [osx]
    - sip ==6.6.2
    - six ==1.16.0
    - smmap ==3.0.5
    - snappy ==1.1.9
    - sniffio ==1.3.0
    - snowballstemmer ==2.2.0
    - soupsieve ==2.3.2.post1
    - sphinx ==5.3.0
    - sphinx-argparse ==0.3.1
    - sphinxcontrib-applehelp ==1.0.2
    - sphinxcontrib-devhelp ==1.0.2
    - sphinxcontrib-htmlhelp ==2.0.0
    - sphinxcontrib-jsmath ==1.0.1
    - sphinxcontrib-qthelp ==1.0.3
    - sphinxcontrib-serializinghtml ==1.1.5
    - sqlite ==3.40.0
    - sqlparse ==0.4.3
    - stack_data ==0.6.1
    - tapi ==1100.0.11  # [osx]
    - tenacity ==8.1.0
    - terminado ==0.17.0
    - threadpoolctl ==3.1.0
    - tinycss2 ==1.2.1
    - tk ==8.6.12
    - toml ==0.10.2
    - tomli ==2.0.1
    - tomlkit ==0.11.6
    - toolz ==0.12.0
    - tornado ==6.2
    - tqdm ==4.64.1
    - traitlets ==5.5.0
    - typing ==3.10.0.0
    - typing-extensions ==4.4.0
    - typing_extensions ==4.4.0
    - tzdata ==2022f
    - unicodedata2 ==15.0.0
    - urllib3 ==1.26.11
    - wcwidth ==0.2.5
    - webencodings ==0.5.1
    - websocket-client ==1.4.2
    - wheel ==0.38.4
    - widgetsnbextension ==4.0.3
    - wrapt ==1.14.1
    - xcb-util ==0.4.0  # [linux]
    - xcb-util-image ==0.4.0  # [linux]
    - xcb-util-keysyms ==0.4.0  # [linux]
    - xcb-util-renderutil ==0.3.9  # [linux]
    - xcb-util-wm ==0.4.1  # [linux]
    - xorg-libxau ==1.0.9
    - xorg-libxdmcp ==1.1.3
    - xyzservices ==2022.9.0
    - xz ==5.2.6
    - yaml ==0.2.5
    - yaml-cpp ==0.7.0
    - zeromq ==4.3.4
    - zipp ==3.10.0
    - zlib ==1.2.13
    - zstd ==1.5.2
