package:
  name: ska3-core
  version: 2019.05.23

requirements:
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:

  # Note that sherpa is not in the defaults channel and may be missed
  # if trying to automatically update ska3-core
   - sherpa ==4.9.1 [linux64 and osx]

  # And note that these packages are presently built out of skare3.
  # If the versions we request become available in conda default channels,
  # it will be fine to move to those default packages and deprecate the
  # skare3 builds
   - astropy ==3.0.3
   - astropy-healpix ==0.4
   - ipywidgets ==7.3.0
   - widgetsnbextension ==3.3.0
   - pytest-arraydiff ==0.2
   - pytest-astropy ==0.4.0
   - pytest-doctestplus ==0.1.3
   - pytest-openfiles ==0.3.0
   - pytest-remotedata ==0.3.0

  # Packages from conda defaults channels, limited to older channels for CentOS5
   - _nb_ext_conf ==0.4.0
   - alabaster ==0.7.10
   - anaconda-client ==1.6.3
   - appnope ==0.1.0 # [osx]
   - asn1crypto ==0.22.0
   - astroid ==1.5.3
   - babel ==2.5.0
   - beautifulsoup4 ==4.6.0
   - bkcharts ==0.2
   - blas ==1.0
   - bleach ==1.5.0
   - bokeh ==0.12.7
   - certifi ==2016.2.28 # [not linux32]
   - cffi ==1.10.0
   - chardet ==3.0.4
   - clyent ==1.2.2
   - configobj ==5.0.6
   - cryptography ==1.8.1
   - curl ==7.54.1
   - cycler ==0.10.0
   - cython ==0.26
   - dbus ==1.10.20 # [linux]
   - decorator ==4.1.2
   - django ==1.11.3
   - docutils ==0.14
   - entrypoints ==0.2.3
   - expat ==2.1.0
   - fontconfig ==2.12.1 # [linux64]
   - freetype ==2.5.5
   - git ==2.9.3 # [linux32]
   - git ==2.11.1 # [linux64 or osx]
   - gitdb2 ==2.0.0
   - gitpython ==2.1.3
   - glib ==2.50.2 # [linux]
   - gst-plugins-base ==1.8.0 # [linux]
   - gstreamer ==1.8.0 # [linux]
   - h5py ==2.7.0
   - hdf5 ==1.8.17
   - html5lib ==0.999
   - icu ==54.1
   - idna ==2.5 # [linux32]
   - idna ==2.6 # [linux64 or osx]
   - imagesize ==0.7.1
   - ipykernel ==4.6.1
   - ipyparallel ==6.0.2
   - ipython ==6.1.0
   - ipython_genutils ==0.2.0
   - isort ==4.2.15
   - jbig ==2.1
   - jedi ==0.10.2
   - jinja2 ==2.9.6
   - jpeg ==9b
   - jsonschema ==2.6.0
   - jupyter ==1.0.0
   - jupyter_client ==5.1.0
   - jupyter_console ==5.2.0
   - jupyter_core ==4.3.0
   - krb5 ==1.13.2
   - lazy-object-proxy ==1.3.1
   - libffi ==3.2.1 # [linux]
   - libgcc ==4.8.5
   - libgfortran ==3.0.0
   - libiconv ==1.14 # [linux]
   - libpng ==1.6.30
   - libsodium ==1.0.10 # [linux]
   - libssh2 ==1.8.0
   - libtiff ==4.0.6
   - libxcb ==1.12 # [linux]
   - libxml2 ==2.9.4 # [linux]
   - libxslt ==1.1.29
   - line_profiler ==2.0
   - llvmlite ==0.18.0
   - lxml ==3.8.0
   - markupsafe ==1.0
   - matplotlib ==2.0.2
   - mistune ==0.7.4
   - mkl ==2017.0.3
   - nb_anacondacloud ==1.4.0
   - nb_conda ==2.2.0
   - nb_conda_kernels ==2.1.0
   - nbconvert ==5.2.1
   - nbformat ==4.4.0
   - nbpresent ==3.0.2
   - networkx ==1.11
   - nose ==1.3.7
   - notebook ==5.0.0
   - numba ==0.33.0
   - numexpr ==2.6.2
   - numpy ==1.12.1
   - numpydoc ==0.7.0
   - olefile ==0.44
   - openssl ==1.0.2l
   - packaging ==16.8
   - pandas ==0.20.3
   - pandocfilters ==1.4.2
   - paramiko ==2.1.2
   - path.py ==10.3.1
   - pcre ==8.39 # [linux]
   - pep8 ==1.7.0
   - pexpect ==4.2.1
   - pickleshare ==0.7.4
   - pillow ==4.2.1
   - pip ==9.0.1
   - pkginfo ==1.4.1 # [linux32]
   - prompt_toolkit ==1.0.15
   - psutil ==5.2.2
   - ptyprocess ==0.5.2
   - py ==1.4.34
   - pyasn1 ==0.2.3
   - pycodestyle ==2.3.1
   - pycosat ==0.6.2 # [linux32]
   - pycparser ==2.17 # [linux32]
   - pycparser ==2.18 # [linux64 or osx]
   - pycrypto ==2.6.1
   - pyflakes ==1.6.0
   - pygments ==2.2.0
   - pylint ==1.7.2
   - pyopenssl ==17.0.0 # [linux32]
   - pyparsing ==2.2.0
   - pyqt ==5.6.0
   - pytables ==3.4.2
   - pytest ==3.2.1
   - python ==3.6.2
   - python-dateutil ==2.6.1
   - python.app ==1.2 # [osx]
   - pytz ==2017.2
   - pyyaml ==3.12
   - pyzmq ==16.0.2
   - qt ==5.6.2
   - qtawesome ==0.4.4
   - qtconsole ==4.3.1
   - qtpy ==1.3.1
   - readline ==6.2
   - requests ==2.14.2
   - rope ==0.9.4
   - runipy ==0.1.5
   - scikit-learn ==0.19.0
   - scipy ==0.19.1
   - setuptools ==27.2.0 # [linux32]
   - setuptools ==36.4.0 # [linux64 or osx]
   - simplegeneric ==0.8.1
   - singledispatch ==3.4.0.3
   - sip ==4.18
   - six ==1.10.0
   - smmap2 ==2.0.1
   - snowballstemmer ==1.2.1
   - sphinx ==1.6.3
   - sphinxcontrib ==1.0
   - sphinxcontrib-websupport ==1.0.1
   - spyder ==3.2.2 # [linux32]
   - spyder ==3.2.3 # [linux64 or osx]
   - sqlite ==3.13.0
   - terminado ==0.6
   - testpath ==0.3.1
   - tk ==8.5.18
   - tornado ==4.5.2
   - traitlets ==4.3.2
   - wcwidth ==0.1.7
   - wheel ==0.29.0
   - wrapt ==1.10.11
   - xz ==5.2.2 # [linux32]
   - xz ==5.2.3 # [linux64 or osx]
   - yaml ==0.1.6
   - zeromq ==4.1.3 # [osx]
   - zeromq ==4.1.5 # [linux]
   - zlib ==1.2.8 # [linux32]
   - zlib ==1.2.11 # [linux64 or osx]
