package:
  name: mica
  version:  {{ SKA_PKG_VERSION }}

build:
  noarch: generic
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/mica


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - testr
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - matplotlib
    - numpy >=1.12.1
    - pytest
    - jinja2
    - astropy
    - ska.shell
    - chandra.time
    - chandra_aca
    - quaternion
    - agasc
    - ska.dbi
    - pytables
    - tables3_api
    - quaternion
    - ska.quatutil
    - ska.matplotlib
    - ska.engarchive
    - kadi
    - pyyaks
    - testr
    - ska.arc5gl
    - ska.astro
    - ska_helpers

test:
  imports:
    - mica


about:
  home: https://github.com/sot/mica

