package:
  name: aca_view
  version:  {{ SKA_PKG_VERSION }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  path: {{ SKA_TOP_SRC_DIR }}/aca_view


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - psutil
    - numpy
    - scipy
    - matplotlib
    - ipython
    - pyqt
    - qtconsole
    - astropy
    - testr
    - maude
    - chandra_aca
    - mica
    - cxotime
    - kadi
    - quaternion
    - ska_matplotlib

test:
  imports:
    - aca_view


about:
  home: https://github.com/sot/aca_view
