package:
  name: ska_matplotlib  # lower case name of package, may contain '-' but no spaces
  version: {{ SKA_PKG_VERSION }}


build:
  script: pip install .
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/ska_matplotlib



requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - ska_helpers

  run:
    - python
    - six
    - matplotlib
    - chandra_time
    - numpy

test:
  imports:
    - Ska.Matplotlib
    - ska_matplotlib

about:
  home: https://github.com/sot/ska_matplotlib
