package:
  name: ska3-core-latest
  version: 2022.2

requirements:
  run:
   - astropy
   - astropy-sphinx-theme
   - astropy-healpix
   - astroquery
   - backports
   - backports.zoneinfo
   - beautifulsoup4
   - bokeh
   - cloudpickle # [win]
   - conda
   - conda-build
   - cython
   - docxtpl
   - django
   - git # [win]
   - gitpython
   - h5py
   - ipympl
   - ipython
   - jinja2
   - jira
   - jplephem
   - jupyter
   - jupyterlab
   - line_profiler
   - lxml
   - mamba
   - matplotlib
   - mpld3
   - nb_conda
   - nbconvert
   - networkx
   - nodejs
   - notebook
   - numba
   - numexpr
   - numpy
   - numpydoc
   - pandas
   - autopep8
   - openpyxl
   - pillow
   - pip
   - flake8
   - pycrypto
   - prompt-toolkit<3.0.0a0 # [win]
   - pylint
   - plotly
   - python-kaleido
   - python-docx
   - pyqtgraph
   - pyyaml
   - qt
   - regions
   - requests
   - rope
   - runipy # [win]
   - scikit-learn
   - scipy
   - setuptools
   - setuptools_scm
   - sherpa # [not win]
   - sphinx-argparse
   - six
   - sphinx
   - sqlalchemy # [win]
   - sqlite
   - tk
   - tqdm
   - yaml
