package:
  name: bep_pcb_check
  version:  {{ SKA_PKG_VERSION }}

build:
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/bep_pcb_check


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm

  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - matplotlib
    - dpa_check
    - acis_thermal_check
    - ska_helpers
    - testr

test:
  imports:
    - bep_pcb_check

about:
  home: https://github.com/acisops/bep_pcb_check

