#!/usr/bin/env python

import os
import argparse

from ska_conda import SkaBuilder

if os.uname().sysname == "Darwin":
    os.environ["MACOSX_DEPLOYMENT_TARGET"] = "10.9"

parser = argparse.ArgumentParser(description="Build Ska Conda packages.")

parser.add_argument("mode", type=str, help="The build mode. Either 'all' for all "
                                           "packages, 'updated' for updated "
                                           "packages, or a specific package name.")
parser.add_argument("--ska_root", type=str, 
                    help="The path to the root directory for the Ska packages. "
                         "Default: /data/acis/ska3_pkg")

args = parser.parse_args()

ska_builder = SkaBuilder(ska_root=args.ska_root)

if args.mode == "all":
    ska_builder.build_all_packages()
elif args.mode == "updated":
    ska_builder.build_updated_packages()
else:
    ska_builder.build_one_package(args.mode)
