#!/usr/bin/env python

import argparse

from ska_conda import SkaBuilder

parser = argparse.ArgumentParser(description="Clone Ska Conda sources.")

parser.add_argument("mode", type=str, help="The clone mode. Either 'all' for all "
                                           "packages, or a specific package name.")
parser.add_argument("--build_root", default=".", type=str,
                    help="The path to the root directory for the Ska packages. "
                         "Default: '.'")

args = parser.parse_args()

ska_builder = SkaBuilder(build_root=args.build_root)

if args.mode == "all":
    ska_builder.clone_all_packages()
else:
    ska_builder.clone_one_package(args.mode)
