#!/usr/bin/env python

import os
import argparse

from ska_conda import SkaBuilder

if os.uname().sysname == "Darwin":
    os.environ["MACOSX_DEPLOYMENT_TARGET"] = "10.9"

parser = argparse.ArgumentParser(description="Build Ska Conda packages.")

parser.add_argument("package", type=str, nargs="?",
                    help="Package to build.  All we be built as needed if none supplied")

parser.add_argument("--build_root", default=".", type=str, 
                    help="The path to the root directory for the Ska packages. "
                         "Default: '.'")

args = parser.parse_args()

ska_builder = SkaBuilder(build_root=args.build_root)

if getattr(args, 'package'):
    ska_builder.build_one_package(args.package)
else:
    ska_builder.build_all_packages()

