package:
  name: sparkles
  version:  {{ SKA_PKG_VERSION }}

build:
  noarch: python
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/sparkles


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - pip
    - setuptools
    - chandra_aca
    - proseco
    - testr
    - numpy >=1.12.1
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - numpy >=1.12.1
    - matplotlib
    - astropy
    - pytest
    - chandra_aca
    - proseco
    - quaternion
    - testr

test:
  imports:
    - sparkles


about:
  home: git@github.com:sot/sparkles

