---
package:
  name: ska3-perl
  version: 2024.1

build:
  skip: True  # [win]

requirements:
  run:
    - _sysroot_linux-64_curr_repodata_hack ==3  # [linux]
    - blas ==1.0  # [linux]
    - ca-certificates ==2023.11.17
    - certifi ==2023.11.17
    - cfitsio ==4.2.0  # [linux]
    - expat ==2.5.0  # [osx]
    - gsl ==2.7  # [linux]
    - kernel-headers_linux-64 ==3.10.0  # [linux]
    - libx11-common-cos7-x86_64 ==1.6.7  # [linux]
    - libx11-cos7-x86_64 ==1.6.7  # [linux]
    - libx11-devel-cos7-x86_64 ==1.6.7  # [linux]
    - mkl-service ==2.4.0  # [linux]
    - mkl_fft ==1.3.8  # [linux]
    - perl ==5.26.2
    - perl-app-cpanminus ==1.7044
    - perl-app-env-ascds ==0.04  # [linux]
    - perl-chandra-time ==0.9.2  # [linux]
    - perl-core-deps ==0.3.1
    - perl-cxc-sysarch ==1.00  # [linux]
    - perl-dbd-sybase ==1.15  # [linux]
    - perl-extended-deps ==0.3.1  # [linux]
    - perl-io-tty ==1.12
    - perl-ska-agasc ==3.5.0  # [linux]
    - perl-ska-classic ==0.6
    - perl-ska-convert ==4.3  # [linux]
    - perl-ska-web ==4.0  # [linux]
    - perl-tk ==804.035  # [linux]
    - pkg-config ==0.29.2
    - sysroot_linux-64 ==2.17  # [linux]
    - task_schedule ==4.3.0
    - watch_cron_logs ==4.2.1
    - xorg-libxft ==2.3.8  # [linux]
    - xtime ==1.2.2  # [linux]
    - zip ==3.0
