package:
  name: fid_drift_mon
  version:  {{ SKA_PKG_VERSION }}

build:
  number: 1
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/fid_drift_mon


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - numpy
    - matplotlib-base
    - astropy
    - pytest
    - chandra_aca
    - cxotime
    - mica
    - quaternion
    - testr
    - ska_helpers

test:
  imports:
    - fid_drift_mon


about:
  home: https://github.com/sot/fid_drift_mon

