package:
  name: xija
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/xija


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - gcc_linux-64 # [linux]
    - libgcc-ng  # [linux]
    - clang_osx-64 # [osx]
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - scipy
    - numba
    - numpy
    - matplotlib
    - ska_matplotlib
    - ska_numpy
    - pyyaks
    - chandra_time
    - testr
    - cheta
    - ska_helpers

test:
  imports:
    - xija


about:
  home: https://github.com/sot/xija
