package:
  name: obc_rate_noise_plots
  version:  {{ SKA_PKG_VERSION }}

build:
  script: |
    pip install .
    mkdir -p $PREFIX/share/obc_rate_noise_plots
    cp task_schedule.cfg $PREFIX/share/obc_rate_noise_plots/

source:
  path: {{ SKA_TOP_SRC_DIR }}/obc_rate_noise_plots

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python
    - matplotlib

about:
  home: https://github.com/sot/obc_rate_noise_plots

