package:
  name: pyyaks
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/pyyaks


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - jinja2
    - testr

test:
  imports:
    - pyyaks
    - pyyaks.context
    - pyyaks.logger
    - pyyaks.fileutil
    - pyyaks.task

about:
  home: https://github.com/sot/pyyaks
  license: BSD
  summary: Pipeline running tools

