package:
  name: chandra.time
  version:  {{ SKA_PKG_VERSION }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  path: {{ SKA_TOP_SRC_DIR }}/Chandra.Time

# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - clangxx_osx-64 # [osx]
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - cython
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - cxotime
    - python
    - six
    - numpy
    - testr
    - ska_helpers

test:
  imports:
    - Chandra.Time


about:
  home: https://github.com/sot/Chandra.Time
  license: BSD
  summary: Chandra Time package
