package:
  name: ska_dbi
  version:  {{ SKA_PKG_VERSION }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/ska_dbi


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - ska_helpers
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - sqlite
    - pytest
    - numpy
    - testr

test:
  imports:
    - Ska.DBI
    - ska_dbi

about:
  home: https://github.com/sot/ska_dbi


